CREATE DATABASE PIZZARIA_JAQUELINE_TB;
USE PIZZARIA_JAQUELINE_TB;

CREATE TABLE CAD_CLI (
IDCLIENTE INT(4) PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
SEXO CHAR(1)
);

CREATE TABLE CLI_TELEFONE (
IDTEL INT(4) PRIMARY KEY AUTO_INCREMENT,
DDD CHAR(2) NOT NULL,
NUMERO VARCHAR(9) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
FK_TEL INT(4),
FOREIGN KEY (FK_TEL) REFERENCES CAD_CLI(IDCLIENTE)
);

CREATE TABLE CLI_ENDERECO (
IDENDERECO INT(4) PRIMARY KEY AUTO_INCREMENT,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(5) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
ESTADO CHAR(2) NOT NULL,
CEP CHAR(8) NOT NULL,
PT_REF VARCHAR(30),
COMPLEMENTO VARCHAR(50),
FK_END INT(4),
FOREIGN KEY (FK_END) REFERENCES CAD_CLI(IDCLIENTE)
);

INSERT INTO CAD_CLI VALUES (
DEFAULT,'MARIA SIRINA DE SOUZA','MARIA234@GMAIL.COM','F'
);

INSERT INTO CAD_CLI VALUES (
DEFAULT,'JUAN BARBOSA FERREIRA DAS DORES',
'JUANZINHO55674@GMAIL.COM','M');

-- INSERINDO O TELEFONE DA MARIA
INSERT INTO CLI_TELEFONE VALUES (
DEFAULT, '11','965963659','CEL',1
);

# INSERINDO O TELEFONE DO JUAN
INSERT INTO CLI_TELEFONE VALUES (
DEFAULT, '16','955962236','CEL',2
);

#ENDEREÇO PARA A MARIA
INSERT INTO CLI_ENDERECO VALUES(
DEFAULT,'RUA DAS CARMELAS','265','SAO PAULO','PARQUE ARARIBA','SP',
'04693000',NULL,NULL,1);

# ENDERECO JUAN
INSERT INTO CLI_ENDERECO VALUES(
DEFAULT,'AVENIDA SANTO AMARO','20365','SAO PAULO','PARQUE DOM BOSCO',
'SP','05968630',NULL,NULL,2);

INSERT INTO CAD_CLI VALUES (
DEFAULT,'Guts Matador','GUTSMATADOR@GMAIL.COM','M');

INSERT INTO CLI_ENDERECO VALUES(
DEFAULT,'AVENIDA JOÃO DIAS','14780','SAO PAULO','JOÃO DIAS',
'SP','05968630',NULL,NULL,3);

INSERT INTO CLI_TELEFONE VALUES (DEFAULT, '11','955962236','CEL',3);

INSERT INTO CAD_CLI VALUES (
DEFAULT,'FRANCISCA CHIQUINHA MADRUGA','CHIQUINHA@GMAIL.COM','F'
);

INSERT INTO CLI_ENDERECO VALUES(
DEFAULT,'AVENIDA SANTO AMARO','20365','SAO PAULO','PARQUE DOM BOSCO',
'SP','05968630',NULL,NULL,4);

INSERT INTO CLI_TELEFONE VALUES (
DEFAULT, '21','963569336','CEL',4
);

INSERT INTO CAD_CLI VALUES (
DEFAULT,'MANOEL ALMEIDA','MANU152@GMAIL.COM','M'
);


INSERT INTO CLI_ENDERECO VALUES(
DEFAULT,'AVENIDA SANTO AMARO','693','SAO PAULO','PARQUE DOM BOSCO',
'SP','05968630',NULL,NULL,5);

INSERT INTO CLI_TELEFONE VALUES (
DEFAULT, '11','932569362','CEL',5
);

SELECT * FROM CLI_ENDERECO;
SELECT * FROM CAD_CLI;
SELECT * FROM CLI_TELEFONE;
    
DESC CLI_TELEFONE;
DESC CLI_ENDERECO;
DESC CAD_CLI;

-- Mostre o endereço da Maria
SELECT NOME, LOGRADOURO, NUMERO, CIDADE, BAIRRO, ESTADO FROM CAD_CLI INNER JOIN CLI_ENDERECO
ON CAD_CLI.IDCLIENTE = CLI_ENDERECO.FK_END WHERE CAD_CLI.IDCLIENTE = 1;

/* MOSTRE O ENDERECO DO GUTS */
SELECT NOME, LOGRADOURO, NUMERO, CIDADE, BAIRRO, ESTADO FROM CAD_CLI 
INNER JOIN CLI_ENDERECO ON CAD_CLI.IDCLIENTE = CLI_ENDERECO.FK_END
WHERE CAD_CLI.IDCLIENTE = 3;

/* MOSTRE O TELEFONE DO GUTS */
SELECT NOME, DDD, NUMERO, TIPO FROM CAD_CLI INNER JOIN CLI_TELEFONE
ON CAD_CLI.IDCLIENTE = CLI_TELEFONE.FK_TEL WHERE CAD_CLI.IDCLIENTE = 3;

/* MOSTRE QUANTOS CLIENTES MORAN NA AVENIDA*/
SELECT NOME, SEXO, LOGRADOURO FROM CAD_CLI INNER JOIN CLI_ENDERECO 
ON CAD_CLI.IDCLIENTE = CLI_ENDERECO.FK_END WHERE LOGRADOURO LIKE 'AVENIDA SANTO AMARO';

/* QUANTOS CLIENTES TEM O DDD 11 */
SELECT count(IDCLIENTE) FROM CAD_CLI INNER JOIN CLI_TELEFONE
ON CAD_CLI.IDCLIENTE = CLI_TELEFONE.FK_TEL WHERE DDD = '11';

/* QUANTIDADE DE MULHERES QUE QUE MORAM NA AVENIDA SANTO AMARO */
SELECT count(IDCLIENTE) AS "QUANTIDADE DE MULHERES", NOME, SEXO, LOGRADOURO FROM CAD_CLI 
INNER JOIN CLI_ENDERECO
ON CAD_CLI.IDCLIENTE = CLI_ENDERECO.FK_END WHERE SEXO LIKE 'F' 
AND LOGRADOURO LIKE 'AVENIDA SANTO AMARO';